[pytest]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    interaction: marks tests as interaction (交互式半自动化用例，默认不执行)
    author(name): specify test author
    serial
addopts = -s --alluredir allure-results --html report.html -m "not interaction"