[pytest]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    interaction: marks tests as interaction (交互式半自动化用例，默认不执行)
    env_hint(requirement): 为测试用例声明环境要求提示
    author(name): specify test author
    serial
addopts =-s --alluredir allure-results --html report.html -m "not interaction"

;log_cli = true
;log_cli_level = INFO
;log_format = %(asctime)s %(levelname)s %(message)s
;log_date_format = %Y-%m-%d %H:%M:%S