class ErrorCode:
    SUCCESS = "0000"
    FAIL = "0001"
    FWTUP001 = "FWTUP001"  # BIOS Upgrade fail
    FWTUP002 = "FWTUP002"  # BMC Upgrade fail
    FWTUP003 = "FWTUP003"  # CPLD Upgrade fail
    FWTUP004 = "FWTUP004"  # HDD/SSD FW upgrade fail
    FWTUP005 = "FWTUP005"  # NIC FW upgrade fail
    FWTUP006 = "FWTUP006"  # RAID/HBA Card FW upgrade fail
    FWTUP007 = "FWTUP007"  # GPU FW upgrade fail
    FWTUP008 = "FWTUP008"  # PSU FW upgrade fail
    FWTUP009 = "FWTUP009"  # Expander FW upgrade fail
    FWTUP00A = "FWTUP00A"  # BP FW Upgrade fail
    FWTUP00B = "FWTUP00B"  # SNIC BIOS Upgrade fail
    FWTUP00C = "FWTUP00C"  # SNIC BMC Upgrade fail
    FWTUP00D = "FWTUP00D"  # PCIE SW FW upgrade fail
    FWTUP00E = "FWTUP00E"  # AEP FW upgrade fail
    FWTUP00F = "FWTUP00F"  # Retimer FW upgrade fail
    FWTUP010 = "FWTUP010"  # Psoc FW upgrade fail
    FWTCH000 = "FWTCH000"  # FW version check fail
    FWTCH001 = "FWTCH001"  # BIOS FW check fail
    FWTCH002 = "FWTCH002"  # BMC FW check fail
    FWTCH003 = "FWTCH003"  # CPLD FW check fail
    FWTCH004 = "FWTCH004"  # HDD/SSD FW check fail
    FWTCH005 = "FWTCH005"  # NIC FW check fail
    FWTCH006 = "FWTCH006"  # RAID/HBA Card FW check fail
    FWTCH007 = "FWTCH007"  # GPU FW check fail
    FWTCH008 = "FWTCH008"  # PSU FW check fail
    FWTCH009 = "FWTCH009"  # Expander FW check fail
    FWTCH00A = "FWTCH00A"  # BP FW check fail
    FWTCH00B = "FWTCH00B"  # SNIC BIOS FW check fail
    FWTCH00C = "FWTCH00C"  # SNIC BMC FW check fail
    FWTCH00D = "FWTCH00D"  # PCIE SW FW check fail
    FWTCH00E = "FWTCH00E"  # AEP FW check fail
    FWTCH00F = "FWTCH00F"  # Retimer FW check fail
    FWTCH010 = "FWTCH010"  # Psoc FW check fail
    FWTCH011 = "FWTCH011"  # TPM FW check fail
    BSTFT001 = "BSTFT001"  # BIOS Checksum Error
    BSTFT002 = "BSTFT002"  # Default CMOS fail
    BSTFT003 = "BSTFT003"  # Set customer request mode fail
    BSTFT004 = "BSTFT004"  # SMBIOS check fail
    BSTFT005 = "BSTFT005"  # UEFI test fail
    BSTFT006 = "BSTFT006"  # export bios config fail
    BSTFT007 = "BSTFT007"  # load bios modify config fail
    BSTFT008 = "BSTFT008"  # Enable ppr fail
    BSTFT009 = "BSTFT009"  # Set BIOS to master
    BSTFT00A = "BSTFT00A"  # Set BIOS to backup
    BSTFT00B = "BSTFT00B"  # Load default BIOS fail
    TEMTCH00 = "TEMTCH00"  # Temperature test fail
    TEMTCH01 = "TEMTCH01"  # CPU temperature fail
    TEMTCH02 = "TEMTCH02"  # MB temperature fail
    TEMTCH03 = "TEMTCH03"  # Inlet temperature fail
    TEMTCH04 = "TEMTCH04"  # Outlet temperature fail
    TEMTCH05 = "TEMTCH05"  # DIMM temperature fail
    TEMTCH06 = "TEMTCH06"  # PCH temperature fail
    TEMTCH07 = "TEMTCH07"  # PS temperature fail
    TEMTCH08 = "TEMTCH08"  # Retimer temperature fail
    TEMTCH09 = "TEMTCH09"  # HDD/SSD temperature fail
    TEMTCH0A = "TEMTCH0A"  # NVME temperature fail
    TEMTCH0B = "TEMTCH0B"  # NIC temperature fail
    TEMTCH0C = "TEMTCH0C"  # OCP temperature fail
    TEMTCH0D = "TEMTCH0D"  # MOC temperature fail
    VOLTCH01 = "VOLTCH01"  # Voltage check fail
    VOLTCH02 = "VOLTCH02"  # System voltage fail
    VOLTCH03 = "VOLTCH03"  # SYS 12V check fail
    VOLTCH04 = "VOLTCH04"  # SYS 5V check fail
    VOLTCH05 = "VOLTCH05"  # SYS 3.3V check fail
    VOLTCH06 = "VOLTCH06"  # RTC battery Voltage check fail
    VOLTCH07 = "VOLTCH07"  # PSU Vout check fail
    HMTFRU01 = "HMTFRU01"  # FRU write fail
    HMTFRU02 = "HMTFRU02"  # FRU check fail
    HMTFRU03 = "HMTFRU03"  # UUID/GUID write fail
    HMTFRU04 = "HMTFRU04"  # UUID/GUID check fail
    HMTMAC01 = "HMTMAC01"  # Get BMC MAC fail from mes
    HMTMAC02 = "HMTMAC02"  # BMC MAC flash fail
    HMTMAC03 = "HMTMAC03"  # BMC MAC check fail
    HMTIP001 = "HMTIP001"  # Get BMC IP fail
    HMTIP002 = "HMTIP002"  # Get hgbox BMC IP fail
    HMTIP003 = "HMTIP003"  # Get jbod usb tty fail
    HMTIP004 = "HMTIP004"  # ping BMC IP fail
    HMTIP005 = "HMTIP005"  # ping hgbox BMC IP fail
    HMTFT001 = "HMTFT001"  # bmc self test fail
    HMTFT002 = "HMTFT002"  # Watchdog test fail
    HMTFT003 = "HMTFT003"  # BMC DRAM test fail
    HMTFT004 = "HMTFT004"  # I2C device fail
    HMTFT005 = "HMTFT005"  # I2C bus fail
    HMTFT006 = "HMTFT006"  # Exec ipmitool sel list fail
    HMTFT007 = "HMTFT007"  # Exec ipmitool sdr list fail
    HMTFT008 = "HMTFT008"  # BMC SEL clear fail
    HMTFT009 = "HMTFT009"  # onekeylog collect fail
    HMTFT00A = "HMTFT00A"  # download onekeylog fail
    HMTFT00B = "HMTFT00B"  # BMC reset fail
    HMTFT00C = "HMTFT00C"  # Load default BMC fail
    HMTFT00D = "HMTFT00D"  # Set BMC to master
    HMTFT00E = "HMTFT00E"  # Set BMC to backup
    HMTST001 = "HMTST001"  # sel list check fail
    HMTST002 = "HMTST002"  # sdr list check fail
    HMTST003 = "HMTST003"  # BMC web page test fail
    HMTST004 = "HMTST004"  # IPMI Remote Power Off Fail
    HMTST005 = "HMTST005"  # IPMI Remote Power On Fail
    LEDT0000 = "LEDT0000"  # LED check fail
    LEDT0001 = "LEDT0001"  # NIC LED check fail
    LEDT0002 = "LEDT0002"  # Memory LED check fail
    LEDT0003 = "LEDT0003"  # HDD active LED check fail
    LEDT0004 = "LEDT0004"  # HDD fault LED check fail
    LEDT0005 = "LEDT0005"  # Fan LED check fail
    LEDT0006 = "LEDT0006"  # PSU LED check fail
    LEDT0007 = "LEDT0007"  # GPU LED check fail
    LEDT0008 = "LEDT0008"  # System health/status LED check fail
    LEDT0009 = "LEDT0009"  # Power BTN LED check fail
    LEDT000A = "LEDT000A"  # UID LED check fail
    LEDT000B = "LEDT000B"  # SAS controller LED check fail
    LEDT000C = "LEDT000C"  # Dedicated BMC LED check fail
    LEDT000D = "LEDT000D"  # Debug LED check fail
    SCTEST00 = "SCTEST00"  # SD Card test fail
    SCTEST01 = "SCTEST01"  # Micro SD Card test fail
    BTTEST00 = "BTTEST00"  # Reset Button test fail
    BTTEST01 = "BTTEST01"  # Power Button test fail
    BTTEST02 = "BTTEST02"  # UID Button test fail
    BTTEST03 = "BTTEST03"  # NMI Button test fail
    CUTCH001 = "CUTCH001"  # CPU Count check fail
    CUTCH002 = "CUTCH002"  # CPU Model check fail
    CUTCH003 = "CUTCH003"  # CPU Location check fail
    CUTCH004 = "CUTCH004"  # CPU Speed check fail
    CUTCH005 = "CUTCH005"  # CPU Core count check fail
    CUTCH006 = "CUTCH006"  # CPU Thread Count check fail
    CUTCH007 = "CUTCH007"  # CPU L1 Cache check fail
    CUTCH008 = "CUTCH008"  # CPU L2 Cache check fail
    CUTCH009 = "CUTCH009"  # CPU L3 Cache check fail
    CUTMCE01 = "CUTMCE01"  # CPU MCE Instruction Fetch Unit error
    CUTMCE02 = "CUTMCE02"  # CPU MCE L1 Data Cache Unit error
    CUTMCE03 = "CUTMCE03"  # CPU MCE  Data Transfer Look-aside Buffer error
    CUTMCE04 = "CUTMCE04"  # CPU MCE Mid Level Cache error
    CUTMCE05 = "CUTMCE05"  # CPU MCE Power Control Unit error
    CUTMCE06 = "CUTMCE06"  # CPU MCE UPI error
    CUTMCE07 = "CUTMCE07"  # CPU MCE UBOX error
    CUTMCE08 = "CUTMCE08"  # CPU McBank error
    CUTMCE09 = "CUTMCE09"  # CPU MCE Fatal machine check error
    CUTFCT01 = "CUTFCT01"  # CPU Hardware Error processor error
    CUTFCT02 = "CUTFCT02"  # CPU fatal error
    CUTFCT03 = "CUTFCT03"  # CPU Configuration Error
    CUTFCT04 = "CUTFCT04"  # CPU Core error
    CUTFCT05 = "CUTFCT05"  # CPU MCERR error
    CUTFCT06 = "CUTFCT06"  # CPU IERR error
    CUTFCT07 = "CUTFCT07"  # CPU CATERR error
    CUTFCT08 = "CUTFCT08"  # CPU Critical Interrupt error
    CUTFCT09 = "CUTFCT09"  # CPU FRB1 BIST error
    CUTFCT0A = "CUTFCT0A"  # CPU FRB2 Hang error
    CUTFCT0B = "CUTFCT0B"  # CPU FRB3 error
    CUTFCT0C = "CUTFCT0C"  # CPU Thermal Trip
    CUTFCT0D = "CUTFCT0D"  # CPU Frequency test fail
    CUTFCT0E = "CUTFCT0E"  # CPU UPI test fail
    CUTFCT10 = "CUTFCT10"  # CPU XGMI function test fail
    CUTFCT11 = "CUTFCT11"  # CPU voltage fail
    CUTSTS00 = "CUTSTS00"  # CPU Stress test fail
    CUTSTS01 = "CUTSTS01"  # CPU linpack test fail
    CUTSTS02 = "CUTSTS02"  # CPU PTU test fail
    CUTSTS03 = "CUTSTS03"  # CPU AMDSST test fail
    CUTSTS04 = "CUTSTS04"  # CPU AMPTTK test fail
    CUTSTS05 = "CUTSTS05"  # CPU XGMI Stress test fail
    MFTCH001 = "MFTCH001"  # Memory Count check fail
    MFTCH002 = "MFTCH002"  # Memory locator check fail
    MFTCH003 = "MFTCH003"  # Memory Vendor check fail
    MFTCH004 = "MFTCH004"  # Memory Speed check fail
    MFTCH005 = "MFTCH005"  # Memory Size check fail
    MFTCH006 = "MFTCH006"  # Memory Part Number check fail
    MFTCH007 = "MFTCH007"  # Memory frequency check fail
    MFTFCT01 = "MFTFCT01"  # Memory Addressing Line Error
    MFTFCT02 = "MFTFCT02"  # Memory Data Line Error
    MFTFCT03 = "MFTFCT03"  # Memory Parity Error
    MFTFCT04 = "MFTFCT04"  # Memory Device Disabled
    MFTFCT05 = "MFTFCT05"  # Memory PPR repair fail
    MFTFCT06 = "MFTFCT06"  # Memory Bit test fail
    MFTFCT07 = "MFTFCT07"  # Memory Single Bit Errors
    MFTFCT08 = "MFTFCT08"  # Memory Uncorrectable ECC Error
    MFTFCT09 = "MFTFCT09"  # Memory Uncorrected patrol scrub error
    MFTFCT0A = "MFTFCT0A"  # Memory Correctable ECC error
    MFTFCT0B = "MFTFCT0B"  # Memory Device Disabled
    MFTFCT0C = "MFTFCT0C"  # Memory Hot
    MFTFCT0D = "MFTFCT0D"  # Memory CMCI STORM
    MFTFCT0E = "MFTFCT0E"  # Memory voltage test fail
    MFTFCT0F = "MFTFCT0F"  # Memory Temperature fail
    MFTFCT10 = "MFTFCT10"  # Memory margin test fail
    MFTFCT11 = "MFTFCT11"  # Memory SPD write fail
    MFTFCT12 = "MFTFCT12"  # Memory SPD test fail
    MFTFCT13 = "MFTFCT13"  # Memory BPS test fail
    MFTMCE01 = "MFTMCE01"  # MCE memory read error
    MFTMCE02 = "MFTMCE02"  # MCE memory write error
    MFTMCE03 = "MFTMCE03"  # Memory MCE addr/cmd error
    MFTMCE04 = "MFTMCE04"  # MCE memory scrubbing error
    MFTMCE05 = "MFTMCE05"  # Memory MCE generic undef request error
    MFTSTS00 = "MFTSTS00"  # Memory Stress test fail
    MFTSTS01 = "MFTSTS01"  # Memory Perf test fail
    MFTSTS02 = "MFTSTS02"  # Memory stressapp test fail
    HDTCH001 = "HDTCH001"  # Disk Count check fail
    HDTCH002 = "HDTCH002"  # Disk Model check fail
    HDTCH003 = "HDTCH003"  # Disk Vendor check fail
    HDTCH004 = "HDTCH004"  # Disk Size check fail
    HDTCH005 = "HDTCH005"  # Disk Type check fail
    HDTCH006 = "HDTCH006"  # Disk Location check fail
    HDTCH007 = "HDTCH007"  # Disk Interface check fail
    HDTCH008 = "HDTCH008"  # SAS/SATA Rate check fail
    HDTFCT01 = "HDTFCT01"  # Disk Link Speed test fail
    HDTFCT02 = "HDTFCT02"  # NVME Width test fail
    HDTFCT03 = "HDTFCT03"  # Disk OP fail
    HDTFCT04 = "HDTFCT04"  # Disk format fail
    HDTFCT05 = "HDTFCT05"  # Disk IO error
    HDTFCT06 = "HDTFCT06"  # Disk Medium error
    HDTFCT07 = "HDTFCT07"  # Disk Phy Err Check fail
    HDTFCT08 = "HDTFCT08"  # Disk critical target error
    HDTFCT09 = "HDTFCT09"  # Disk IO offline error
    HDTFCT0A = "HDTFCT0A"  # Disk Unrecovered read error
    HDTFCT0B = "HDTFCT0B"  # Disk Internal target failure
    HDTFCT0C = "HDTFCT0C"  # Disk Unhandled error code
    HDTFCT0D = "HDTFCT0D"  # Disk drive fault
    HDTFCT0E = "HDTFCT0E"  # Disk FPDMA error
    HDTFCT0F = "HDTFCT0F"  # Disk ata error
    HDTFCT10 = "HDTFCT10"  # Disk Smart log check fail
    HDTFCT11 = "HDTFCT11"  # NVME Smart Critical Warning
    HDTFCT12 = "HDTFCT12"  # NVME Smart Temperature Error
    HDTFCT13 = "HDTFCT13"  # NVME Media Errors
    HDTFCT14 = "HDTFCT14"  # NVME Smart num_err_log_entries error
    HDTFCT15 = "HDTFCT15"  # NVME Smart crc error
    HDTFCT16 = "HDTFCT16"  # NVME Smart end_to_end_error
    HDTFCT17 = "HDTFCT17"  # NVME Capacitance Health error
    HDTFCT18 = "HDTFCT18"  # NVME Percentage used error
    HDTFCT19 = "HDTFCT19"  # NVME available spare fail
    HDTFCT1A = "HDTFCT1A"  # Disk SMART ENABLED ERROR
    HDTFCT1B = "HDTFCT1B"  # Disk Smart OVERALL-HEALTH fail
    HDTFCT1C = "HDTFCT1C"  # SSD Smart ID check fail
    HDTFCT1D = "HDTFCT1D"  # HDD Smart ID check fail
    HDTFCT1E = "HDTFCT1E"  # Disk Smart Temperature Error
    HDTFCT1F = "HDTFCT1F"  # Disk Smartlog show Pre-fail
    HDTFCT20 = "HDTFCT20"  # Disk pending sector error
    HDTFCT21 = "HDTFCT21"  # Disk Power on hours fail
    HDTFCT22 = "HDTFCT22"  # SSD Wearout error
    HDTSTS01 = "HDTSTS01"  # Disk Perf test fail
    HDTSTS02 = "HDTSTS02"  # Disk Stress test fail
    USTAFT01 = "USTAFT01"  # USB Device count check fail
    USTAFT02 = "USTAFT02"  # USB 2.0 speed fail
    USTAFT03 = "USTAFT03"  # USB 3.0 speed fail
    USTAFT04 = "USTAFT04"  # USB controller test fail
    SPTFCT01 = "SPTFCT01"  # Serial Port test fail
    SPTFCT02 = "SPTFCT02"  # Internal Interrupt test fail
    SPTFCT03 = "SPTFCT03"  # Internal Loopback test fail
    SPTFCT04 = "SPTFCT04"  # External Loopback test fail
    SPTFCT05 = "SPTFCT05"  # Baud Rate Test fail
    PETALW01 = "PETALW01"  # PCIe Width check fail
    PETALS01 = "PETALS01"  # PCIe Link Speed check fail
    PETACC01 = "PETACC01"  # PCIe configuration check fail
    PETERR01 = "PETERR01"  # PCIe Bus Fatal Error
    PETERR02 = "PETERR02"  # PCIe UCE Errs
    PETERR03 = "PETERR03"  # PCIe AER Errs
    PETERR04 = "PETERR04"  # PCIe error
    PETERR05 = "PETERR05"  # PCIe transmit timed out
    PETERR06 = "PETERR06"  # Mellanox PhyError check failed
    PCI00001 = "PCI00001"  # PCI configuration check fail
    VPDTA001 = "VPDTA001"  # VPD flash fail
    VPDTA002 = "VPDTA002"  # FRU ID check fail
    VPDTA003 = "VPDTA003"  # VPD check fail
    TPMTA001 = "TPMTA001"  # TPM enable fail
    TPMTA002 = "TPMTA002"  # TPM disable fail
    TPMTA003 = "TPMTA003"  # TPM Status check fail
    TPMTA004 = "TPMTA004"  # TPM test fail
    EXPTA001 = "EXPTA001"  # Expander temperature check fail
    EXPTA002 = "EXPTA002"  # Expander Phy Err Check Fail
    EXPTA003 = "EXPTA003"  # Expander offline device error
    EXPTA004 = "EXPTA004"  # Expander Link Check Fail
    RADTA001 = "RADTA001"  # Controller config check fail
    RADTA002 = "RADTA002"  # Controller default config set fail
    RADTA003 = "RADTA003"  # Controller default config check fail
    RADTA004 = "RADTA004"  # Controller customer config set fail
    RADTA005 = "RADTA005"  # Controller customer config check fail
    RADTA006 = "RADTA006"  # Controller battery test fail
    RADTA007 = "RADTA007"  # HBA temperature check fail
    RADTA008 = "RADTA008"  # HBA Phy Err Check Fail
    RADTA009 = "RADTA009"  # PMC health status
    RADTA00A = "RADTA00A"  # HBA offline device error
    RADTA00B = "RADTA00B"  # HBA Link Check Fail
    GPUTCH01 = "GPUTCH01"  # GPU Count check fail
    GPUTCH02 = "GPUTCH02"  # GPU Model check fail
    GPUTCH03 = "GPUTCH03"  # GPU VBIOS check fail
    GPUTCH04 = "GPUTCH04"  # GPU Default Power Limit check fail
    GPUTCH05 = "GPUTCH05"  # GPU Enforced Power Limit check fail
    GPUTCH06 = "GPUTCH06"  # GPU FRU info test fail
    GPUTFT01 = "GPUTFT01"  # GPU p2pBandwidthLatencyTest fail
    GPUTFT02 = "GPUTFT02"  # GPU bandwidthTest fail
    GPUTFT03 = "GPUTFT03"  # GPU temperature check fail
    GPUTFT04 = "GPUTFT04"  # GPU Power cables error
    GPUTFT05 = "GPUTFT05"  # GPU has ERR message in nvidia-smi
    GPUTFT06 = "GPUTFT06"  # GPU exist ECC error
    GPUTFT07 = "GPUTFT07"  # GPU insufficiently powered
    GPUTFT08 = "GPUTFT08"  # GPU has infoROM is corrupted
    GPUTFT09 = "GPUTFT09"  # GPU XID error
    GPUTFT0A = "GPUTFT0A"  # GPU fallen off error
    GPUTFT0B = "GPUTFT0B"  # Error running nbody stress test
    GPUTFT0C = "GPUTFT0C"  # lost GPU cards
    GPUTFT0D = "GPUTFT0D"  # GPU clocks throttle reasons
    GPUTFT0E = "GPUTFT0E"  # GPU cannot be accessed successfully
    GPUTST01 = "GPUTST01"  # GPU nbody stress test fail
    GPUTST02 = "GPUTST02"  # GPU DCGM Stress test fail
    GPUTST03 = "GPUTST03"  # GPU Stress test fail
    GPUTST04 = "GPUTST04"  # GPU Perf test fail
    GPUTST05 = "GPUTST05"  # Nvqual PCI Express Qualification Test fail
    GPUTST06 = "GPUTST06"  # Nvqual PCI Express Bandwidth Test fail
    GPUTST07 = "GPUTST07"  # Nvuqal NVLink Qualification Test fail
    PSUTCH01 = "PSUTCH01"  # PSU AC lost
    PSUTCH02 = "PSUTCH02"  # PSU watt check fail
    PSUTCH03 = "PSUTCH03"  # PSU Count check fail
    PSUTCH04 = "PSUTCH04"  # PSU Model check fail
    PSUTCH05 = "PSUTCH05"  # PSU manufacturer check fail
    PSUTCH06 = "PSUTCH06"  # PSU locator check fail
    PSUTFT01 = "PSUTFT01"  # Get PSU rated power fail
    PSUTFT02 = "PSUTFT02"  # Get PSU current watt fail
    PSUTFT03 = "PSUTFT03"  # PSU Power status fault
    PSUTFT04 = "PSUTFT04"  # PSU Redundancy lost
    NICTCH01 = "NICTCH01"  # NIC config info check fail
    NICTCH02 = "NICTCH02"  # NIC count check fail
    NICTCH03 = "NICTCH03"  # NIC location check fail
    NICTCH04 = "NICTCH04"  # NIC address check fail
    NICTCH05 = "NICTCH05"  # NIC device id check fail
    NICTCH06 = "NICTCH06"  # NIC vendor check fail
    NICTCH07 = "NICTCH07"  # NIC subdevice check fail
    NICTCH08 = "NICTCH08"  # NIC subvendor check fail
    NICTCH09 = "NICTCH09"  # NIC MAC Address check fail
    NICTFT01 = "NICTFT01"  # NIC Link Speed check fail
    NICTFT02 = "NICTFT02"  # NIC width check fail
    NICTFT03 = "NICTFT03"  # NIC NCSI test fail
    NICTFT04 = "NICTFT04"  # NIC loop back test fail
    SNICT001 = "SNICT001"  # Not Found SNIC
    SNICT002 = "SNICT002"  # SNIC FPGA test fail
    SNICT003 = "SNICT003"  # SNIC Stress test fail
    SNICT004 = "SNICT004"  # SNIC test fail
    SNICT005 = "SNICT005"  # SNIC PCIe test fail
    SNICT006 = "SNICT006"  # SNIC I2C test fail
    SNICT007 = "SNICT007"  # SNIC phy error
    FANTCH01 = "FANTCH01"  # FAN config info check fail
    FANTCH02 = "FANTCH02"  # FAN count check fail
    FANTFT01 = "FANTFT01"  # Get FAN speed fail
    FANTFT02 = "FANTFT02"  # FAN speed test fail
    FANTFT03 = "FANTFT03"  # Set FAN auto mode fail
    FANTFT04 = "FANTFT04"  # Set FAN manual mode fail
    FANTFT05 = "FANTFT05"  # Set FAN speed fail
    FANTFT06 = "FANTFT06"  # FAN RPM range test fail
    BPTCH001 = "BPTCH001"  # Backplane check fail
    BPTCH002 = "BPTCH002"  # Backplane location check fail
    BPTCH003 = "BPTCH003"  # Backplane id check fail
    BPTCH004 = "BPTCH004"  # Backplane user code check fail
    BPTCH005 = "BPTCH005"  # Backplane sel log check fail
    RTCTST01 = "RTCTST01"  # RTC Clock check fail
    VGATST01 = "VGATST01"  # VGA test fail
    VGATST02 = "VGATST02"  # Rear VGA test fail
    VGATST03 = "VGATST03"  # Front VGA test fail
    HUTAF001 = "HUTAF001"  # System Test Hang Up
    HUTAF002 = "HUTAF002"  # Memory Test Hang Up
    HUTAF003 = "HUTAF003"  # Keyboard Test Hang Up
    HUTAF004 = "HUTAF004"  # Video Test Hang Up
    HUTAF005 = "HUTAF005"  # Paralle Port Test Hang Up
    HUTAF006 = "HUTAF006"  # Serial Port Test Hang Up
    HUTAF007 = "HUTAF007"  # Disk Test Hang Up
    HUTAF008 = "HUTAF008"  # CPU Test Hang Up
    HUTAF009 = "HUTAF009"  # BIOS Test Hang Up
    HUTAF00A = "HUTAF00A"  # NIC Test Hang Up
    HUTAF00B = "HUTAF00B"  # USB Test Hang Up
    HUTAF00C = "HUTAF00C"  # Firmware Test Hang Up
    HUTAF00D = "HUTAF00D"  # Preload Test Hang Up
    HUTAF00E = "HUTAF00E"  # IPMI Test Hang Up
    HUTAF00F = "HUTAF00F"  # PCIe Test Hang Up
    HUTAF010 = "HUTAF010"  # Digital or Analog Test
    HUTAF011 = "HUTAF011"  # KVM-over-IP Test Hang Up
    HUTAF012 = "HUTAF012"  # BIOS POST Hang Up
    HUTAF013 = "HUTAF013"  # No Power
    HUTAF014 = "HUTAF014"  # No Display
    HUTAF015 = "HUTAF015"  # Other Test Hang Up
    MESTCH01 = "MESTCH01"  # Fail to get info from mes
    MESTCH02 = "MESTCH02"  # fail to get CTO info from mes
    MESTCH03 = "MESTCH03"  # fail to get FW Version info from mes
    MESTCH04 = "MESTCH04"  # fail to get component info from mes
    OSTST001 = "OSTST001"  # Get OS IP fail
    OSTST002 = "OSTST002"  # OS version error
    OSTST003 = "OSTST003"  # get hwclock time_stamp fail
    OSTST004 = "OSTST004"  # get date time_stamp fail
    OSTST005 = "OSTST005"  # exec dmesg fail
    OSTST006 = "OSTST006"  # cat messages fail
    OSTST007 = "OSTST007"  # Utilities install fail
    OSTST008 = "OSTST008"  # Driver install fail
    OSTST009 = "OSTST009"  # Any Utilities not installed
    OSTST00A = "OSTST00A"  # Any Driver not installed
    OSTST00B = "OSTST00B"  # nvme not installed
    OSTST00C = "OSTST00C"  # smartctl not installed
    OSTST00D = "OSTST00D"  # lspci not installed
    SYST0001 = "SYST0001"  # Test Not Complete
    SYST0002 = "SYST0002"  # Chassis Intrusion error
    SYST0003 = "SYST0003"  # System time check fail
    OTTA0001 = "OTTA0001"  # Scan/Input label fail
    OTTA0002 = "OTTA0002"  # MB POWER Drop Stat
    OTTA0003 = "OTTA0003"  # TSC unstable
    OTTA0004 = "OTTA0004"  # Critical Interrupt
    OTTA0005 = "OTTA0005"  # SEL log
    OTTA0006 = "OTTA0006"  # message error
    OTTA0007 = "OTTA0007"  # dmesg error
    OTTA0008 = "OTTA0008"  # EDAC check fail
    OTTA0009 = "OTTA0009"  # mce error
    FFFFFFFF = "FFFFFFFF"  # Unknown Error
